import type { FeedbackItem, Notification, Shipment } from "./types";

export const demoAccounts = [
  {
    role: "Broker Admin",
    email: "admin@harborbridge.demo",
    password: "DemoAdmin123!",
  },
  {
    role: "Shipper",
    email: "shipper@harborbridge.demo",
    password: "DemoShipper123!",
  },
  {
    role: "Shipping Line Guest",
    email: "guest access via share link",
    password: "No password required",
  },
];

export const shipments: Shipment[] = [
  {
    id: "electronics-singapore-rotterdam",
    reference: "HB-2026-0001",
    shipperName: "Lion City Electronics Pte Ltd",
    consigneeName: "Rotterdam Device Distribution BV",
    notifyParty: "Rotterdam Device Distribution BV",
    cargoDescription: "Consumer electronics and accessories",
    itemType: "Electronics",
    hsCode: "8517.62",
    packageCount: 428,
    dimensions: "40 cartons, mixed pallet stack",
    grossWeightKg: 8420,
    netWeightKg: 7980,
    volumeCbm: 58.4,
    incoterm: "FOB",
    origin: "Singapore",
    destination: "Rotterdam, Netherlands",
    pol: "Singapore",
    pod: "Rotterdam",
    containerType: "40HC",
    etd: "2026-07-03",
    eta: "2026-08-04",
    carrier: "Maersk",
    bookingNumber: "MAEU-SG-48291",
    blNumber: "MAEU760128391",
    containerNumber: "MSKU1234567",
    status: "booking_confirmed",
    documentStatus: "approved",
    blStatus: "Draft B/L issued",
    nextAction: "Client to approve draft B/L",
    notes: "Priority retail replenishment shipment.",
    lastUpdated: "2026-06-21T09:20:00+08:00",
    cargoItems: [
      {
        description: "Routers, tablets, chargers, and accessories",
        itemType: "Electronics",
        hsCode: "8517.62",
        packages: 428,
        dimensions: "120 x 100 x 140 cm pallets",
        grossWeightKg: 8420,
        netWeightKg: 7980,
        volumeCbm: 58.4,
      },
    ],
    documents: [
      {
        id: "doc-1001-ci",
        type: "Commercial invoice",
        fileName: "HB-2026-0001-commercial-invoice.pdf",
        uploadedBy: "Demo Admin",
        uploadedAt: "2026-06-17T10:10:00+08:00",
        status: "approved",
      },
      {
        id: "doc-1001-pl",
        type: "Packing list",
        fileName: "HB-2026-0001-packing-list.pdf",
        uploadedBy: "Demo Admin",
        uploadedAt: "2026-06-17T10:18:00+08:00",
        status: "approved",
      },
      {
        id: "doc-1001-bl",
        type: "Draft B/L",
        fileName: "HB-2026-0001-draft-bl.pdf",
        uploadedBy: "Maersk Line Guest",
        uploadedAt: "2026-06-21T09:04:00+08:00",
        status: "uploaded",
      },
    ],
    timeline: [
      {
        milestone: "Draft created",
        status: "completed",
        timestamp: "2026-06-14T11:30:00+08:00",
        responsibleParty: "Broker",
        notes: "Shipment pack created.",
        source: "manual",
      },
      {
        milestone: "Documents reviewed",
        status: "completed",
        timestamp: "2026-06-18T15:40:00+08:00",
        responsibleParty: "Broker",
        notes: "Commercial invoice and packing list approved.",
        source: "manual",
      },
      {
        milestone: "Draft B/L issued",
        status: "completed",
        timestamp: "2026-06-21T09:04:00+08:00",
        responsibleParty: "Shipping line",
        notes: "Draft B/L uploaded for client review.",
        source: "shipping_line_guest",
      },
      {
        milestone: "Draft B/L approved",
        status: "pending",
        responsibleParty: "Shipper",
        notes: "Awaiting consignee address confirmation.",
        source: "manual",
      },
    ],
    comments: [
      {
        userName: "Maersk Line Guest",
        role: "shipping_line_guest",
        timestamp: "2026-06-21T09:06:00+08:00",
        message: "Draft B/L has been uploaded. Please confirm consignee address spelling.",
      },
      {
        userName: "Demo Admin",
        role: "admin",
        timestamp: "2026-06-21T10:12:00+08:00",
        message: "Address is under client review. Target approval by tomorrow.",
      },
    ],
    auditLogs: [
      {
        action: "shipment_created",
        actor: "Demo Admin",
        role: "admin",
        timestamp: "2026-06-14T11:30:00+08:00",
        detail: "Created shipment HB-2026-0001.",
      },
      {
        action: "bl_uploaded",
        actor: "Maersk Line Guest",
        role: "shipping_line_guest",
        timestamp: "2026-06-21T09:04:00+08:00",
        detail: "Uploaded draft B/L.",
      },
    ],
    billOfLading: {
      number: "MAEU760128391",
      type: "Original B/L",
      status: "Draft issued",
      issuedAt: "2026-06-21T09:04:00+08:00",
      notes: "Awaiting shipper approval.",
    },
    shareLinks: [
      {
        token: "demo-share-electronics",
        recipientCompany: "Maersk",
        recipientName: "Maersk Line Guest",
        recipientEmail: "carrier-demo@example.com",
        expiresAt: "2026-07-22T00:00:00+08:00",
        lastViewedAt: "2026-06-21T09:06:00+08:00",
        canComment: true,
        canUploadDocuments: true,
        canUpdateStatus: true,
      },
    ],
  },
  {
    id: "furniture-vietnam-los-angeles",
    reference: "HB-2026-0002",
    shipperName: "Saigon Modern Furniture Co",
    consigneeName: "Pacific Home Imports LLC",
    notifyParty: "Pacific Home Imports LLC",
    cargoDescription: "Flat-pack furniture sets",
    itemType: "Furniture",
    hsCode: "9403.60",
    packageCount: 960,
    dimensions: "960 cartons across 22 pallets",
    grossWeightKg: 12600,
    netWeightKg: 11940,
    volumeCbm: 69.8,
    incoterm: "CIF",
    origin: "Ho Chi Minh City, Vietnam",
    destination: "Los Angeles, USA",
    pol: "Cat Lai",
    pod: "Los Angeles",
    containerType: "40HC",
    etd: "2026-07-08",
    eta: "2026-08-01",
    carrier: "ONE",
    bookingNumber: "ONEY-SGN-77018",
    containerNumber: "TCLU7788990",
    status: "shared_with_line",
    documentStatus: "shared_with_line",
    blStatus: "Not issued",
    nextAction: "Awaiting carrier booking confirmation",
    notes: "Buyer requested earliest possible sailing.",
    lastUpdated: "2026-06-21T14:15:00+08:00",
    cargoItems: [
      {
        description: "Flat-pack dining and bedroom furniture",
        itemType: "Furniture",
        hsCode: "9403.60",
        packages: 960,
        dimensions: "120 x 100 x 145 cm pallets",
        grossWeightKg: 12600,
        netWeightKg: 11940,
        volumeCbm: 69.8,
      },
    ],
    documents: [
      {
        id: "doc-1002-ci",
        type: "Commercial invoice",
        fileName: "HB-2026-0002-commercial-invoice.pdf",
        uploadedBy: "Demo Shipper",
        uploadedAt: "2026-06-19T16:22:00+08:00",
        status: "shared_with_line",
      },
      {
        id: "doc-1002-booking",
        type: "Booking confirmation",
        fileName: "pending-booking-confirmation.pdf",
        uploadedBy: "Not uploaded",
        uploadedAt: "",
        status: "not_uploaded",
      },
    ],
    timeline: [
      {
        milestone: "Shared with shipping line",
        status: "completed",
        timestamp: "2026-06-20T13:00:00+08:00",
        responsibleParty: "Broker",
        notes: "Share link sent to carrier desk.",
        source: "manual",
      },
      {
        milestone: "Booking requested",
        status: "in_progress",
        timestamp: "2026-06-21T14:15:00+08:00",
        responsibleParty: "Shipping line",
        notes: "Carrier reviewing equipment availability.",
        source: "shipping_line_guest",
      },
      {
        milestone: "Booking confirmed",
        status: "pending",
        responsibleParty: "Shipping line",
        notes: "Expected next carrier update today.",
        source: "manual",
      },
    ],
    comments: [
      {
        userName: "ONE Booking Desk",
        role: "shipping_line_guest",
        timestamp: "2026-06-21T14:15:00+08:00",
        message: "Equipment is available. Awaiting final shipping instructions.",
      },
    ],
    auditLogs: [
      {
        action: "shipment_shared",
        actor: "Demo Admin",
        role: "admin",
        timestamp: "2026-06-20T13:00:00+08:00",
        detail: "Created shipping line share link for ONE Booking Desk.",
      },
    ],
    shareLinks: [
      {
        token: "demo-share-furniture",
        recipientCompany: "ONE",
        recipientName: "ONE Booking Desk",
        recipientEmail: "carrier-demo@example.com",
        expiresAt: "2026-07-22T00:00:00+08:00",
        lastViewedAt: "2026-06-21T14:15:00+08:00",
        canComment: true,
        canUploadDocuments: true,
        canUpdateStatus: true,
      },
    ],
  },
  {
    id: "reefer-thailand-tokyo",
    reference: "HB-2026-0003",
    shipperName: "Andaman Fresh Seafood Ltd",
    consigneeName: "Tokyo Bay Foods KK",
    notifyParty: "Tokyo Bay Foods KK",
    cargoDescription: "Frozen seafood, reefer controlled",
    itemType: "Reefer seafood",
    hsCode: "0306.17",
    packageCount: 520,
    dimensions: "520 foam boxes, reefer stow",
    grossWeightKg: 9100,
    netWeightKg: 8700,
    volumeCbm: 42.2,
    incoterm: "CFR",
    origin: "Bangkok, Thailand",
    destination: "Tokyo, Japan",
    pol: "Laem Chabang",
    pod: "Tokyo",
    containerType: "40RF",
    etd: "2026-07-01",
    eta: "2026-07-11",
    carrier: "Ocean Network Express",
    bookingNumber: "ONEY-TH-22810",
    blNumber: "ONEYTH22810SWB",
    containerNumber: "RFSU4455667",
    status: "in_transit",
    documentStatus: "accepted_by_line",
    blStatus: "Sea waybill issued",
    nextAction: "Monitor temperature logs and ETA",
    notes: "Temperature set point -18 C.",
    lastUpdated: "2026-06-21T17:45:00+08:00",
    cargoItems: [
      {
        description: "Frozen shrimp and mixed seafood cartons",
        itemType: "Reefer seafood",
        hsCode: "0306.17",
        packages: 520,
        dimensions: "100 x 80 x 105 cm stacks",
        grossWeightKg: 9100,
        netWeightKg: 8700,
        volumeCbm: 42.2,
      },
    ],
    documents: [
      {
        id: "doc-1003-swb",
        type: "Final B/L / sea waybill",
        fileName: "HB-2026-0003-sea-waybill.pdf",
        uploadedBy: "ONE Line Guest",
        uploadedAt: "2026-06-20T08:30:00+08:00",
        status: "accepted_by_line",
      },
    ],
    timeline: [
      {
        milestone: "Loaded on vessel",
        status: "completed",
        timestamp: "2026-06-20T23:10:00+08:00",
        responsibleParty: "Shipping line",
        notes: "Reefer loaded and sailing confirmed.",
        source: "shipping_line_guest",
      },
      {
        milestone: "Vessel sailed",
        status: "completed",
        timestamp: "2026-06-21T06:30:00+08:00",
        responsibleParty: "Operations",
        notes: "Manual timeline updated by operations.",
        source: "manual",
      },
      {
        milestone: "Arrived at destination port",
        status: "pending",
        responsibleParty: "Shipping line",
        notes: "Expected Tokyo arrival July 11.",
        source: "system",
      },
    ],
    comments: [
      {
        userName: "Demo Shipper",
        role: "shipper",
        timestamp: "2026-06-21T17:45:00+08:00",
        message: "Please flag any ETA change immediately due to supermarket delivery window.",
      },
    ],
    auditLogs: [
      {
        action: "status_changed",
        actor: "Demo Admin",
        role: "admin",
        timestamp: "2026-06-21T06:30:00+08:00",
        detail: "Updated milestone to Vessel sailed.",
      },
    ],
    billOfLading: {
      number: "ONEYTH22810SWB",
      type: "Sea waybill",
      status: "Issued",
      issuedAt: "2026-06-20T08:30:00+08:00",
      notes: "Final sea waybill issued.",
    },
    shareLinks: [],
  },
  {
    id: "dg-singapore-dubai",
    reference: "HB-2026-0004",
    shipperName: "Merlion Specialty Chemicals Pte Ltd",
    consigneeName: "Gulf Industrial Supplies FZE",
    notifyParty: "Gulf Industrial Supplies FZE",
    cargoDescription: "DG chemicals, Class 3 flammable liquid",
    itemType: "Dangerous goods",
    hsCode: "3814.00",
    packageCount: 80,
    dimensions: "80 steel drums on 20 pallets",
    grossWeightKg: 15200,
    netWeightKg: 14400,
    volumeCbm: 31.6,
    incoterm: "DAP",
    origin: "Singapore",
    destination: "Dubai, UAE",
    pol: "Singapore",
    pod: "Jebel Ali",
    containerType: "20GP",
    etd: "2026-07-12",
    eta: "2026-07-28",
    carrier: "CMA CGM",
    status: "docs_review",
    documentStatus: "needs_review",
    blStatus: "Not issued",
    nextAction: "Resolve MSDS and DG declaration review comments",
    notes: "Requires DG acceptance before booking request.",
    lastUpdated: "2026-06-21T18:05:00+08:00",
    cargoItems: [
      {
        description: "Class 3 solvent blend in sealed steel drums",
        itemType: "Dangerous goods",
        hsCode: "3814.00",
        packages: 80,
        dimensions: "110 x 110 x 130 cm pallet stacks",
        grossWeightKg: 15200,
        netWeightKg: 14400,
        volumeCbm: 31.6,
      },
    ],
    documents: [
      {
        id: "doc-1004-msds",
        type: "MSDS",
        fileName: "HB-2026-0004-msds.pdf",
        uploadedBy: "Demo Shipper",
        uploadedAt: "2026-06-21T10:14:00+08:00",
        status: "needs_review",
        rejectionReason: "UN number missing from page 2.",
      },
      {
        id: "doc-1004-dg",
        type: "DG declaration",
        fileName: "HB-2026-0004-dg-declaration.pdf",
        uploadedBy: "Demo Shipper",
        uploadedAt: "2026-06-21T10:18:00+08:00",
        status: "needs_review",
        rejectionReason: "Carrier needs flash point confirmation.",
      },
    ],
    timeline: [
      {
        milestone: "Documents reviewed",
        status: "blocked",
        timestamp: "2026-06-21T18:05:00+08:00",
        responsibleParty: "Broker",
        notes: "DG documents need corrections before carrier submission.",
        source: "manual",
      },
      {
        milestone: "Shared with shipping line",
        status: "pending",
        responsibleParty: "Broker",
        notes: "Blocked until DG package is corrected.",
        source: "manual",
      },
    ],
    comments: [
      {
        userName: "Demo Admin",
        role: "admin",
        timestamp: "2026-06-21T18:05:00+08:00",
        message: "MSDS and DG declaration need revision before sharing with the line.",
      },
    ],
    auditLogs: [
      {
        action: "document_rejected",
        actor: "Demo Admin",
        role: "admin",
        timestamp: "2026-06-21T18:05:00+08:00",
        detail: "Requested revisions for MSDS and DG declaration.",
      },
    ],
    shareLinks: [],
  },
];

export const feedback: FeedbackItem[] = [
  {
    id: "feedback-1",
    submittedBy: "Client Reviewer",
    pageOrFeature: "Shipment detail tabs",
    comment: "The tabs make it easy to separate cargo, documents, and comments. Add a print/export pack later.",
    priority: "medium",
    status: "open",
    createdAt: "2026-06-21T15:10:00+08:00",
  },
  {
    id: "feedback-2",
    submittedBy: "Client Reviewer",
    pageOrFeature: "Dashboard",
    comment: "Please make delayed or blocked shipments more visually obvious.",
    priority: "high",
    status: "reviewed",
    createdAt: "2026-06-21T16:32:00+08:00",
  },
];

export const notifications: Notification[] = [
  {
    title: "Draft B/L ready",
    message: "Maersk uploaded a draft B/L for HB-2026-0001.",
    shipmentReference: "HB-2026-0001",
    createdAt: "2026-06-21T09:06:00+08:00",
  },
  {
    title: "Documents need review",
    message: "MSDS and DG declaration need corrections before carrier sharing.",
    shipmentReference: "HB-2026-0004",
    createdAt: "2026-06-21T18:05:00+08:00",
  },
];

export const milestoneCatalog = [
  "Draft created",
  "Documents uploaded",
  "Documents reviewed",
  "Shared with shipping line",
  "Booking requested",
  "Booking confirmed",
  "Shipping instructions submitted",
  "Draft B/L issued",
  "Draft B/L approved",
  "Final B/L / Sea Waybill issued",
  "Container gated in",
  "Loaded on vessel",
  "Vessel sailed",
  "Arrived at destination port",
  "Discharged",
  "Customs cleared",
  "Delivered",
  "Closed",
];

export const documentTypes = [
  "Commercial invoice",
  "Packing list",
  "Certificate of origin",
  "MSDS",
  "DG declaration",
  "Export permit",
  "Import permit",
  "Insurance certificate",
  "Booking confirmation",
  "Shipping instructions",
  "Draft B/L",
  "Final B/L / sea waybill",
  "VGM declaration",
  "Other",
];

export function getShipment(id: string) {
  return shipments.find((shipment) => shipment.id === id);
}

export function getShipmentByShareToken(token: string) {
  return shipments.find((shipment) =>
    shipment.shareLinks.some((shareLink) => shareLink.token === token),
  );
}
